version: "3"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  # postgres:
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=mysecretpassword
  #     - POSTGRES_DB=mydatabase
  #   ports:
  #     - "5432:5432"
